sudo: required
services:
  - docker

before_install:
  - docker build -t wendelluiz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wendelluiz/react-test npm test

after_sucess:
  - docker build -t wendelluiz/multi-client ./client
  - docker build -t wendelluiz/multi-nginx ./nginx
  - docker build -t wendelluiz/multi-server ./server
  - docker build -t wendelluiz/multi-worker ./worker
  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push wendelluiz/multi-client
  - docker push wendelluiz/multi-nginx
  - docker push wendelluiz/multi-server
  - docker push wendelluiz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker2
  env: Multidocker2-env
  bucket_name: elasticbeanstalk-us-east-2-539255213441
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY